### ISSUE TITLE
Generate a deep dictionary representation of Command

### ISSUE THREAD

**Issue by einari** [dolittle/DotNET.SDK#19]
In the interest of time we're now going between JSON and then to a Dictionary in CommandToCommandRequestConverter. 

This works as expected, but we should obviously not have to go via a serializer - and a very specific as well for this.

Look into providing a deep creation of these things in Fundamentals - reusable fundamental piece

**Comment by woksin** [comment]
There is a problem handling CommandRequests from frontend through a CommandCoordinator when we have multiple Commands with the same name.

I think that it's related to this issue, @einari 

If you can group Commands per namespace in a dictionary that would help solve the problem?

**Comment by woksin** [comment]
To add more information to the comment I made above:
We have these two commands in the Domain (taken from the Command Proxies endpoint):
"CBS#UserManagement.StaffUser-ChangeLocation+Command|Domain"
and
"CBS#UserManagement.DataCollector-ChangeLocation+Command|Domain"

When coordinating a command from the front end I get this Exception message:
"Sequence contains more than one element"
With stacktrace:
"   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Dolittle.Applications.ApplicationStructureMap.GetBestMatchingTypeFor(IEnumerable`1 types)
   at Dolittle.Applications.ApplicationArtifactResolver.Resolve(IApplicationArtifactIdentifier identifier)
   at Dolittle.Commands.Handling.CommandRequestToCommandConverter.Convert(CommandRequest request)
   at Dolittle.Commands.Validation.CommandValidator.Validate(CommandRequest command)
   at Dolittle.Runtime.Commands.Validation.CommandValidators.Validate(CommandRequest command)
   at Dolittle.Runtime.Commands.Coordination.CommandCoordinator.Handle(ITransaction transaction, CommandRequest command)"

The command.type is = "CBS#UserManagement.DataCollector-ChangeLocation+Command|Domain"
